[features]
seeds = false
skip-lint = false
[programs.devnet]
stake = "37HsMb2NSamepLG98j7MyYiB9E5tDBzsPYWVmoR32sJ2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://frosty-floral-wind.solana-devnet.quiknode.pro/fa3c7dec03be0b5335ff2905b342eedf94ada834/"
wallet = "/home/sixvxsh/Programming/blockchain/keys/ChangeableStake/AuthChangeStakeProg.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
